"""initial_schema_scoped_by_pump

Revision ID: 19166713937b
Revises: 
Create Date: 2026-07-14 23:37:12.345593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19166713937b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pumps',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_pumps_code'), 'pumps', ['code'], unique=True)
    op.create_index(op.f('ix_pumps_id'), 'pumps', ['id'], unique=False)
    op.create_index(op.f('ix_pumps_uuid'), 'pumps', ['uuid'], unique=True)
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'OPERATOR', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_table', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.String(length=100), nullable=False),
    sa.Column('changes_json', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('customers',
    sa.Column('customer_code', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('gst_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('outstanding_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('pump_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['pumps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_customer_code'), 'customers', ['customer_code'], unique=True)
    op.create_index(op.f('ix_customers_gst_number'), 'customers', ['gst_number'], unique=True)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_mobile'), 'customers', ['mobile'], unique=True)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_index(op.f('ix_customers_pump_id'), 'customers', ['pump_id'], unique=False)
    op.create_index(op.f('ix_customers_uuid'), 'customers', ['uuid'], unique=True)
    op.create_table('employees',
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('pump_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['pumps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_pump_id'), 'employees', ['pump_id'], unique=False)
    op.create_index(op.f('ix_employees_uuid'), 'employees', ['uuid'], unique=True)
    op.create_table('fuel_dispensers',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'MAINTENANCE', 'OUT_OF_ORDER', name='nozzlestatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('pump_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['pumps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_dispensers_id'), 'fuel_dispensers', ['id'], unique=False)
    op.create_index(op.f('ix_fuel_dispensers_pump_id'), 'fuel_dispensers', ['pump_id'], unique=False)
    op.create_index(op.f('ix_fuel_dispensers_uuid'), 'fuel_dispensers', ['uuid'], unique=True)
    op.create_table('fuel_tanks',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('fuel_type', sa.Enum('PETROL', 'SPEED', 'DIESEL', 'LUBRICANT', name='fueltype'), nullable=False),
    sa.Column('capacity_liters', sa.Float(), nullable=False),
    sa.Column('current_stock_liters', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('pump_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['pumps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_tanks_id'), 'fuel_tanks', ['id'], unique=False)
    op.create_index(op.f('ix_fuel_tanks_pump_id'), 'fuel_tanks', ['pump_id'], unique=False)
    op.create_index(op.f('ix_fuel_tanks_uuid'), 'fuel_tanks', ['uuid'], unique=True)
    op.create_table('price_schedules',
    sa.Column('fuel_type', sa.Enum('PETROL', 'SPEED', 'DIESEL', 'LUBRICANT', name='fueltype'), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_applied', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('pump_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['pumps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_schedules_effective_from'), 'price_schedules', ['effective_from'], unique=False)
    op.create_index(op.f('ix_price_schedules_id'), 'price_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_price_schedules_pump_id'), 'price_schedules', ['pump_id'], unique=False)
    op.create_index(op.f('ix_price_schedules_uuid'), 'price_schedules', ['uuid'], unique=True)
    op.create_table('user_pump_access',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pump_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['pumps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'pump_id', name='uq_user_pump')
    )
    op.create_index(op.f('ix_user_pump_access_id'), 'user_pump_access', ['id'], unique=False)
    op.create_index(op.f('ix_user_pump_access_pump_id'), 'user_pump_access', ['pump_id'], unique=False)
    op.create_index(op.f('ix_user_pump_access_user_id'), 'user_pump_access', ['user_id'], unique=False)
    op.create_table('dip_readings',
    sa.Column('tank_id', sa.Integer(), nullable=False),
    sa.Column('reading_date', sa.Date(), nullable=False),
    sa.Column('opening_dip_liters', sa.Float(), nullable=False),
    sa.Column('closing_dip_liters', sa.Float(), nullable=False),
    sa.Column('sales_liters_calculated', sa.Float(), nullable=False),
    sa.Column('actual_sales_from_vouchers', sa.Float(), nullable=False),
    sa.Column('variance_liters', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('pump_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['pumps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tank_id'], ['fuel_tanks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dip_readings_id'), 'dip_readings', ['id'], unique=False)
    op.create_index(op.f('ix_dip_readings_pump_id'), 'dip_readings', ['pump_id'], unique=False)
    op.create_index(op.f('ix_dip_readings_reading_date'), 'dip_readings', ['reading_date'], unique=False)
    op.create_index(op.f('ix_dip_readings_tank_id'), 'dip_readings', ['tank_id'], unique=False)
    op.create_index(op.f('ix_dip_readings_uuid'), 'dip_readings', ['uuid'], unique=True)
    op.create_table('ledger_entries',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.Enum('OPENING_BALANCE', 'VOUCHER', 'PAYMENT', 'DEBIT_ADJUSTMENT', 'CREDIT_ADJUSTMENT', name='ledgerentrytype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('reference_type', sa.String(length=20), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('pump_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['pump_id'], ['pumps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_customer_id'), 'ledger_entries', ['customer_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_entry_date'), 'ledger_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_ledger_entries_id'), 'ledger_entries', ['id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_pump_id'), 'ledger_entries', ['pump_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_reference_id'), 'ledger_entries', ['reference_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_uuid'), 'ledger_entries', ['uuid'], unique=True)
    op.create_table('nozzles',
    sa.Column('dispenser_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('fuel_type', sa.Enum('PETROL', 'SPEED', 'DIESEL', 'LUBRICANT', name='fueltype'), nullable=False),
    sa.Column('last_reading', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'MAINTENANCE', 'OUT_OF_ORDER', name='nozzlestatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('pump_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dispenser_id'], ['fuel_dispensers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pump_id'], ['pumps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nozzles_dispenser_id'), 'nozzles', ['dispenser_id'], unique=False)
    op.create_index(op.f('ix_nozzles_id'), 'nozzles', ['id'], unique=False)
    op.create_index(op.f('ix_nozzles_pump_id'), 'nozzles', ['pump_id'], unique=False)
    op.create_index(op.f('ix_nozzles_uuid'), 'nozzles', ['uuid'], unique=True)
    op.create_table('payments',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_mode', sa.Enum('CASH', 'UPI', 'CARD', 'CREDIT', name='paymentmode'), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('reference_number', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('tally_status', sa.Enum('PENDING', 'SYNCED', 'FAILED', name='tallystatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('pump_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['pump_id'], ['pumps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_customer_id'), 'payments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_payment_date'), 'payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_payments_pump_id'), 'payments', ['pump_id'], unique=False)
    op.create_index(op.f('ix_payments_uuid'), 'payments', ['uuid'], unique=True)
    op.create_table('shift_timetables',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_timetables_id'), 'shift_timetables', ['id'], unique=False)
    op.create_index(op.f('ix_shift_timetables_uuid'), 'shift_timetables', ['uuid'], unique=True)
    op.create_table('shifts',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opening_cash', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('closing_cash_reported', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_sales_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cash_reconciled', sa.Boolean(), nullable=False),
    sa.Column('variance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('pump_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['pump_id'], ['pumps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_id'), 'shifts', ['id'], unique=False)
    op.create_index(op.f('ix_shifts_pump_id'), 'shifts', ['pump_id'], unique=False)
    op.create_index(op.f('ix_shifts_uuid'), 'shifts', ['uuid'], unique=True)
    op.create_table('vehicles',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('pump_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['pump_id'], ['pumps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_customer_id'), 'vehicles', ['customer_id'], unique=False)
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_pump_id'), 'vehicles', ['pump_id'], unique=False)
    op.create_index(op.f('ix_vehicles_uuid'), 'vehicles', ['uuid'], unique=True)
    op.create_index(op.f('ix_vehicles_vehicle_number'), 'vehicles', ['vehicle_number'], unique=True)
    op.create_table('nozzle_readings',
    sa.Column('nozzle_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('reading_date', sa.Date(), nullable=False),
    sa.Column('opening_reading', sa.Float(), nullable=False),
    sa.Column('closing_reading', sa.Float(), nullable=False),
    sa.Column('sales', sa.Float(), nullable=False),
    sa.Column('total_sales', sa.Float(), nullable=False),
    sa.Column('sales_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('pump_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nozzle_id'], ['nozzles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pump_id'], ['pumps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nozzle_readings_id'), 'nozzle_readings', ['id'], unique=False)
    op.create_index(op.f('ix_nozzle_readings_nozzle_id'), 'nozzle_readings', ['nozzle_id'], unique=False)
    op.create_index(op.f('ix_nozzle_readings_pump_id'), 'nozzle_readings', ['pump_id'], unique=False)
    op.create_index(op.f('ix_nozzle_readings_reading_date'), 'nozzle_readings', ['reading_date'], unique=False)
    op.create_index(op.f('ix_nozzle_readings_shift_id'), 'nozzle_readings', ['shift_id'], unique=False)
    op.create_index(op.f('ix_nozzle_readings_uuid'), 'nozzle_readings', ['uuid'], unique=True)
    op.create_table('vouchers',
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=20), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('nozzle_id', sa.Integer(), nullable=True),
    sa.Column('fuel_type', sa.Enum('PETROL', 'SPEED', 'DIESEL', 'LUBRICANT', name='fueltype'), nullable=False),
    sa.Column('quantity_liters', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('rate_per_liter', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_mode', sa.Enum('CASH', 'UPI', 'CARD', 'CREDIT', name='paymentmode'), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_status', sa.Enum('UNPAID', 'PARTIAL', 'PAID', name='paymentstatus'), nullable=False),
    sa.Column('ai_provider', sa.Enum('GEMINI', 'OPENROUTER', 'OLLAMA', name='aiprovider'), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='verificationstatus'), nullable=False),
    sa.Column('tally_status', sa.Enum('PENDING', 'SYNCED', 'FAILED', name='tallystatus'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('pump_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['nozzle_id'], ['nozzles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pump_id'], ['pumps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number', 'invoice_date', name='uq_invoice_number_date')
    )
    op.create_index(op.f('ix_vouchers_customer_id'), 'vouchers', ['customer_id'], unique=False)
    op.create_index(op.f('ix_vouchers_id'), 'vouchers', ['id'], unique=False)
    op.create_index(op.f('ix_vouchers_invoice_date'), 'vouchers', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_vouchers_invoice_number'), 'vouchers', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_vouchers_nozzle_id'), 'vouchers', ['nozzle_id'], unique=False)
    op.create_index(op.f('ix_vouchers_pump_id'), 'vouchers', ['pump_id'], unique=False)
    op.create_index(op.f('ix_vouchers_uuid'), 'vouchers', ['uuid'], unique=True)
    op.create_index(op.f('ix_vouchers_vehicle_id'), 'vouchers', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_vouchers_vehicle_number'), 'vouchers', ['vehicle_number'], unique=False)
    op.create_table('voucher_settlements',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('pump_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pump_id'], ['pumps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voucher_settlements_id'), 'voucher_settlements', ['id'], unique=False)
    op.create_index(op.f('ix_voucher_settlements_payment_id'), 'voucher_settlements', ['payment_id'], unique=False)
    op.create_index(op.f('ix_voucher_settlements_pump_id'), 'voucher_settlements', ['pump_id'], unique=False)
    op.create_index(op.f('ix_voucher_settlements_uuid'), 'voucher_settlements', ['uuid'], unique=True)
    op.create_index(op.f('ix_voucher_settlements_voucher_id'), 'voucher_settlements', ['voucher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voucher_settlements_voucher_id'), table_name='voucher_settlements')
    op.drop_index(op.f('ix_voucher_settlements_uuid'), table_name='voucher_settlements')
    op.drop_index(op.f('ix_voucher_settlements_pump_id'), table_name='voucher_settlements')
    op.drop_index(op.f('ix_voucher_settlements_payment_id'), table_name='voucher_settlements')
    op.drop_index(op.f('ix_voucher_settlements_id'), table_name='voucher_settlements')
    op.drop_table('voucher_settlements')
    op.drop_index(op.f('ix_vouchers_vehicle_number'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_vehicle_id'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_uuid'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_pump_id'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_nozzle_id'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_invoice_number'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_invoice_date'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_id'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_customer_id'), table_name='vouchers')
    op.drop_table('vouchers')
    op.drop_index(op.f('ix_nozzle_readings_uuid'), table_name='nozzle_readings')
    op.drop_index(op.f('ix_nozzle_readings_shift_id'), table_name='nozzle_readings')
    op.drop_index(op.f('ix_nozzle_readings_reading_date'), table_name='nozzle_readings')
    op.drop_index(op.f('ix_nozzle_readings_pump_id'), table_name='nozzle_readings')
    op.drop_index(op.f('ix_nozzle_readings_nozzle_id'), table_name='nozzle_readings')
    op.drop_index(op.f('ix_nozzle_readings_id'), table_name='nozzle_readings')
    op.drop_table('nozzle_readings')
    op.drop_index(op.f('ix_vehicles_vehicle_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_uuid'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_pump_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_customer_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_shifts_uuid'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_pump_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_shift_timetables_uuid'), table_name='shift_timetables')
    op.drop_index(op.f('ix_shift_timetables_id'), table_name='shift_timetables')
    op.drop_table('shift_timetables')
    op.drop_index(op.f('ix_payments_uuid'), table_name='payments')
    op.drop_index(op.f('ix_payments_pump_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_customer_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_nozzles_uuid'), table_name='nozzles')
    op.drop_index(op.f('ix_nozzles_pump_id'), table_name='nozzles')
    op.drop_index(op.f('ix_nozzles_id'), table_name='nozzles')
    op.drop_index(op.f('ix_nozzles_dispenser_id'), table_name='nozzles')
    op.drop_table('nozzles')
    op.drop_index(op.f('ix_ledger_entries_uuid'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_reference_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_pump_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_entry_date'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_customer_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_dip_readings_uuid'), table_name='dip_readings')
    op.drop_index(op.f('ix_dip_readings_tank_id'), table_name='dip_readings')
    op.drop_index(op.f('ix_dip_readings_reading_date'), table_name='dip_readings')
    op.drop_index(op.f('ix_dip_readings_pump_id'), table_name='dip_readings')
    op.drop_index(op.f('ix_dip_readings_id'), table_name='dip_readings')
    op.drop_table('dip_readings')
    op.drop_index(op.f('ix_user_pump_access_user_id'), table_name='user_pump_access')
    op.drop_index(op.f('ix_user_pump_access_pump_id'), table_name='user_pump_access')
    op.drop_index(op.f('ix_user_pump_access_id'), table_name='user_pump_access')
    op.drop_table('user_pump_access')
    op.drop_index(op.f('ix_price_schedules_uuid'), table_name='price_schedules')
    op.drop_index(op.f('ix_price_schedules_pump_id'), table_name='price_schedules')
    op.drop_index(op.f('ix_price_schedules_id'), table_name='price_schedules')
    op.drop_index(op.f('ix_price_schedules_effective_from'), table_name='price_schedules')
    op.drop_table('price_schedules')
    op.drop_index(op.f('ix_fuel_tanks_uuid'), table_name='fuel_tanks')
    op.drop_index(op.f('ix_fuel_tanks_pump_id'), table_name='fuel_tanks')
    op.drop_index(op.f('ix_fuel_tanks_id'), table_name='fuel_tanks')
    op.drop_table('fuel_tanks')
    op.drop_index(op.f('ix_fuel_dispensers_uuid'), table_name='fuel_dispensers')
    op.drop_index(op.f('ix_fuel_dispensers_pump_id'), table_name='fuel_dispensers')
    op.drop_index(op.f('ix_fuel_dispensers_id'), table_name='fuel_dispensers')
    op.drop_table('fuel_dispensers')
    op.drop_index(op.f('ix_employees_uuid'), table_name='employees')
    op.drop_index(op.f('ix_employees_pump_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_customers_uuid'), table_name='customers')
    op.drop_index(op.f('ix_customers_pump_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_mobile'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_gst_number'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_code'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_pumps_uuid'), table_name='pumps')
    op.drop_index(op.f('ix_pumps_id'), table_name='pumps')
    op.drop_index(op.f('ix_pumps_code'), table_name='pumps')
    op.drop_table('pumps')
    # ### end Alembic commands ###
