"""add_period_start_end_to_daily_sheets

Revision ID: 44e5dce5cfe0
Revises: 74be757ae153
Create Date: 2026-07-15 13:54:43.060825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44e5dce5cfe0'
down_revision: Union[str, Sequence[str], None] = '74be757ae153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_sheets', sa.Column('period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('daily_sheets', sa.Column('period_end', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_sheets', 'period_end')
    op.drop_column('daily_sheets', 'period_start')
    # ### end Alembic commands ###
