"""add_testing_liters

Revision ID: 48eed73943a5
Revises: b5b1be8b0476
Create Date: 2026-07-20 15:53:29.403958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from alembic_helpers.idempotent import add_column_if_missing, drop_column_if_exists


# revision identifiers, used by Alembic.
revision: str = '48eed73943a5'
down_revision: Union[str, Sequence[str], None] = 'b5b1be8b0476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Idempotent: the column may already exist from init_db.check_and_update_schema()'s
    # backfill on prod DBs built by create_all. See alembic_helpers/idempotent.py.
    add_column_if_missing('nozzle_readings', sa.Column('testing_liters', sa.Float(), nullable=False, server_default='0.0'))
    # Skip index/foreign key recreate if they already exist or cause errors in SQLite.
    try:
        op.create_index(op.f('ix_nozzles_tank_id'), 'nozzles', ['tank_id'], unique=False)
        op.create_foreign_key(None, 'nozzles', 'fuel_tanks', ['tank_id'], ['id'], ondelete='SET NULL')
    except Exception:
        pass
    try:
        op.create_index(op.f('ix_vehicles_normalized_number'), 'vehicles', ['normalized_number'], unique=False)
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_index(op.f('ix_vehicles_normalized_number'), table_name='vehicles')
    except Exception:
        pass
    try:
        op.drop_constraint(None, 'nozzles', type_='foreignkey')
        op.drop_index(op.f('ix_nozzles_tank_id'), table_name='nozzles')
    except Exception:
        pass
    drop_column_if_exists('nozzle_readings', 'testing_liters')
    # ### end Alembic commands ###
