"""add_procurement_rate_and_nps_rating

Revision ID: 4bc2474a5d81
Revises: e1f2a3b4c5d6
Create Date: 2026-07-22 09:21:18.900053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bc2474a5d81'
down_revision: Union[str, Sequence[str], None] = 'e1f2a3b4c5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nps_ratings',
    sa.Column('voucher_id', sa.Integer(), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('pump_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['pumps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nps_ratings_id'), 'nps_ratings', ['id'], unique=False)
    op.create_index(op.f('ix_nps_ratings_pump_id'), 'nps_ratings', ['pump_id'], unique=False)
    op.create_index(op.f('ix_nps_ratings_token'), 'nps_ratings', ['token'], unique=True)
    op.create_index(op.f('ix_nps_ratings_uuid'), 'nps_ratings', ['uuid'], unique=True)
    op.create_index(op.f('ix_nps_ratings_voucher_id'), 'nps_ratings', ['voucher_id'], unique=False)
    op.drop_index(op.f('ix_daily_sheets_date'), table_name='daily_sheets')
    op.drop_index(op.f('ix_daily_sheets_id'), table_name='daily_sheets')
    op.drop_index(op.f('ix_daily_sheets_pump_id'), table_name='daily_sheets')
    op.drop_index(op.f('ix_daily_sheets_uuid'), table_name='daily_sheets')
    op.drop_table('daily_sheets')
    op.add_column('nozzle_readings', sa.Column('return_testing_to_storage', sa.Boolean(), nullable=True))
    op.execute("UPDATE nozzle_readings SET return_testing_to_storage = TRUE")
    op.alter_column('nozzle_readings', 'return_testing_to_storage', nullable=False)
    op.add_column('tanker_deliveries', sa.Column('procurement_rate', sa.Float(), nullable=True))
    op.alter_column('tanker_deliveries', 'pump_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('tanker_deliveries_uuid_key'), 'tanker_deliveries', type_='unique')
    op.create_index(op.f('ix_tanker_deliveries_id'), 'tanker_deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_tanker_deliveries_pump_id'), 'tanker_deliveries', ['pump_id'], unique=False)
    op.create_index(op.f('ix_tanker_deliveries_tank_id'), 'tanker_deliveries', ['tank_id'], unique=False)
    op.create_index(op.f('ix_tanker_deliveries_uuid'), 'tanker_deliveries', ['uuid'], unique=True)
    op.drop_constraint(op.f('tanker_deliveries_pump_id_fkey'), 'tanker_deliveries', type_='foreignkey')
    op.create_foreign_key(None, 'tanker_deliveries', 'pumps', ['pump_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tanker_deliveries', type_='foreignkey')
    op.create_foreign_key(op.f('tanker_deliveries_pump_id_fkey'), 'tanker_deliveries', 'pumps', ['pump_id'], ['id'])
    op.drop_index(op.f('ix_tanker_deliveries_uuid'), table_name='tanker_deliveries')
    op.drop_index(op.f('ix_tanker_deliveries_tank_id'), table_name='tanker_deliveries')
    op.drop_index(op.f('ix_tanker_deliveries_pump_id'), table_name='tanker_deliveries')
    op.drop_index(op.f('ix_tanker_deliveries_id'), table_name='tanker_deliveries')
    op.create_unique_constraint(op.f('tanker_deliveries_uuid_key'), 'tanker_deliveries', ['uuid'], postgresql_nulls_not_distinct=False)
    op.alter_column('tanker_deliveries', 'pump_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('tanker_deliveries', 'procurement_rate')
    op.drop_column('nozzle_readings', 'return_testing_to_storage')
    op.create_table('daily_sheets',
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('manual_sheet_image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('pump_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('period_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('period_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('manual_payment_mode_amounts_data', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pump_id'], ['pumps.id'], name=op.f('daily_sheets_pump_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('daily_sheets_pkey')),
    sa.UniqueConstraint('pump_id', 'date', name=op.f('uq_daily_sheet_pump_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_daily_sheets_uuid'), 'daily_sheets', ['uuid'], unique=True)
    op.create_index(op.f('ix_daily_sheets_pump_id'), 'daily_sheets', ['pump_id'], unique=False)
    op.create_index(op.f('ix_daily_sheets_id'), 'daily_sheets', ['id'], unique=False)
    op.create_index(op.f('ix_daily_sheets_date'), 'daily_sheets', ['date'], unique=False)
    op.drop_index(op.f('ix_nps_ratings_voucher_id'), table_name='nps_ratings')
    op.drop_index(op.f('ix_nps_ratings_uuid'), table_name='nps_ratings')
    op.drop_index(op.f('ix_nps_ratings_token'), table_name='nps_ratings')
    op.drop_index(op.f('ix_nps_ratings_pump_id'), table_name='nps_ratings')
    op.drop_index(op.f('ix_nps_ratings_id'), table_name='nps_ratings')
    op.drop_table('nps_ratings')
    # ### end Alembic commands ###
