"""add_tally_status_to_payments

Revision ID: 5d42468ae07a
Revises: 08ebb62c1d6b
Create Date: 2026-07-13 14:05:47.552835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d42468ae07a'
down_revision: Union[str, Sequence[str], None] = '08ebb62c1d6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('tally_status', sa.Enum('PENDING', 'SYNCED', 'FAILED', name='tallystatus'), nullable=False, server_default='PENDING'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'tally_status')
    # ### end Alembic commands ###
