"""add_daily_sheets

Revision ID: 74be757ae153
Revises: 19166713937b
Create Date: 2026-07-15 02:53:57.004157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74be757ae153'
down_revision: Union[str, Sequence[str], None] = '19166713937b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_sheets',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('manual_sheet_image', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('pump_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['pumps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pump_id', 'date', name='uq_daily_sheet_pump_date')
    )
    op.create_index(op.f('ix_daily_sheets_date'), 'daily_sheets', ['date'], unique=False)
    op.create_index(op.f('ix_daily_sheets_id'), 'daily_sheets', ['id'], unique=False)
    op.create_index(op.f('ix_daily_sheets_pump_id'), 'daily_sheets', ['pump_id'], unique=False)
    op.create_index(op.f('ix_daily_sheets_uuid'), 'daily_sheets', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_sheets_uuid'), table_name='daily_sheets')
    op.drop_index(op.f('ix_daily_sheets_pump_id'), table_name='daily_sheets')
    op.drop_index(op.f('ix_daily_sheets_id'), table_name='daily_sheets')
    op.drop_index(op.f('ix_daily_sheets_date'), table_name='daily_sheets')
    op.drop_table('daily_sheets')
    # ### end Alembic commands ###
